import { NextRequest, NextResponse } from 'next/server'
import { getSession } from '@/lib/auth'
import { db } from '@/lib/db'

/**
 * GET /api/agents/content - Get content queue (social media posts generated by Content Marketing Agent)
 */
export async function GET(req: NextRequest) {
  const session = await getSession()
  if (!session || session.role !== 'admin') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { searchParams } = new URL(req.url)
  const status = searchParams.get('status')
  const platform = searchParams.get('platform')
  const limit = parseInt(searchParams.get('limit') || '50')

  const where: any = {}
  if (status) where.status = status
  if (platform) where.platform = platform

  const content = await db.contentQueue.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    take: limit,
  })

  const stats = {
    total: await db.contentQueue.count(),
    draft: await db.contentQueue.count({ where: { status: 'draft' } }),
    scheduled: await db.contentQueue.count({ where: { status: 'scheduled' } }),
    posted: await db.contentQueue.count({ where: { status: 'posted' } }),
    byPlatform: {
      facebook: await db.contentQueue.count({ where: { platform: 'facebook' } }),
      instagram: await db.contentQueue.count({ where: { platform: 'instagram' } }),
      tiktok: await db.contentQueue.count({ where: { platform: 'tiktok' } }),
    },
  }

  return NextResponse.json({ content, stats })
}

/**
 * POST - Update content status (approve/schedule/delete)
 */
export async function POST(req: NextRequest) {
  const session = await getSession()
  if (!session || session.role !== 'admin') {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { contentId, action } = await req.json()
  // action: 'approve' | 'schedule' | 'delete'

  if (action === 'delete') {
    await db.contentQueue.delete({ where: { id: contentId } })
    return NextResponse.json({ success: true, message: 'Content deleted' })
  }

  const statusMap: Record<string, string> = {
    approve: 'scheduled',
    schedule: 'scheduled',
  }

  const content = await db.contentQueue.update({
    where: { id: contentId },
    data: { status: statusMap[action] || 'scheduled' },
  })

  return NextResponse.json({ success: true, content })
}
